<a href="https://colab.research.google.com/github/aguilargallardo/DS-Unit-1-Sprint-3-Linear-Algebra/blob/master/module1-vectors-and-matrices/Copy_of_LS_DS_131_Vectors_and_Matrices_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1 - Scalars and Vectors

For the questions below it is not sufficient to simply provide answer to the questions, but you must solve the problems and show your work using python (the NumPy library will help a lot!) Translate the vectors and matrices into their appropriate python  representations and use numpy or functions that you write yourself to demonstrate the result or property. 

## 1.1 Create a two-dimensional vector and plot it on a graph

In [0]:
import numpy as np
import math
import matplotlib.pyplot as plt

In [190]:
x = np.array([[1,0],[1,1]])

plt.figure(figsize=(10,10))
plt.plot(x)
#plt.arrow(0,0, blue[0], blue[0],head_width=.05, head_length=.05, color='blue');
plt.xlim(-1,2)
plt.ylim(-1,2)

<IPython.core.display.Javascript object>

(-1, 2)

<IPython.core.display.Javascript object>

## 1.2 Create a three-dimensional vecor and plot it on a graph

In [191]:
y = np.array([[1,0],[1,1], [-1,0]])

blue = np.multiply(1, y)
plt.figure(figsize=(10,10))
plt.plot(y)
plt.xlim(-1,2)
plt.ylim(-1,2)

<IPython.core.display.Javascript object>

(-1, 2)

<IPython.core.display.Javascript object>

In [192]:
from mpl_toolkits.mplot3d import Axes3D
import numpy as np

vectors = np.array([[0, 0, 0, 1, 0, 0], 
                    [0, 0, 0, 1, 1, 0],
                    [0, 0, 0, -1, 0, 0]])


X, Y, Z, U, V, W = zip(*vectors)
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.quiver(X, Y, Z, U, V, W, length=1)
ax.set_xlim([0, 5])
ax.set_ylim([0, 5])
ax.set_zlim([0, 5])
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
plt.show()

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [0]:
%matplotlib notebook
plt.rcParams['figure.figsize'] = (6,4)
plt.rcParams['figure.dpi'] = 150

In [194]:
fig = plt.figure()
ax = fig.add_subplot(111, projection = '3d')
plt.show()

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

## 1.3 Scale the vectors you created in 1.1 by $5$, $\pi$, and $-e$ and plot all four vectors (original + 3 scaled vectors) on a graph. What do you notice about these vectors? 

In [195]:
from math import e, pi
print(e)
print(pi)

2.718281828459045
3.141592653589793


In [196]:
x1 = np.multiply(5, x)
x2 = np.multiply(pi, x)
x3 = np.multiply(-e, x)
plt.figure(figsize=(10,10))
#plt.arrow(0, 0, x1, head_width =.4, color = 'y')
#plt.arrow(0, 0, 3, 4, head_width = .4, color = 'r')
#plt.arrow(0, 0, 5, 7, head_width =.4, color = 'y')
#plt.arrow(0, 0, 3, 4, head_width = .4, color = 'r')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [197]:
x1

array([[5, 0],
       [5, 5]])

## 1.4 Graph vectors $\vec{a}$ and $\vec{b}$ and plot them on a graph

\begin{align}
\vec{a} = \begin{bmatrix} 5 \\ 7 \end{bmatrix}
\qquad
\vec{b} = \begin{bmatrix} 3 \\4 \end{bmatrix}
\end{align}

In [198]:
a = np.array([5, 7])
b = np.array([3, 4])

plt.figure(figsize=(10,10))
plt.arrow(0, 0, 5, 7, head_width =.4, color = 'y')
plt.arrow(0, 0, 3, 4, head_width = .4, color = 'r')
plt.xlim(0,6)
plt.ylim(0,8)
#plt.arrow(0, 0, 5, 7, head_width=.02, head_length=.01, color='y')

<IPython.core.display.Javascript object>

(0, 8)

<IPython.core.display.Javascript object>

## 1.5 find $\vec{a} - \vec{b}$ and plot the result on the same graph as $\vec{a}$ and $\vec{b}$. Is there a relationship between vectors $\vec{a} \thinspace, \vec{b} \thinspace \text{and} \thinspace \vec{a-b}$

In [199]:
c = np.subtract(a,b)
c

array([2, 3])

In [200]:
plt.figure(figsize=(10,10))
plt.arrow(0, 0, 5, 7, head_width =.4, color = 'y')
plt.arrow(0, 0, 3, 4, head_width = .4, color = 'r')
plt.arrow(0, 0, 2, 3, head_width = .4, color = 'b')
plt.xlim(0,6)
plt.ylim(0,8)

<IPython.core.display.Javascript object>

(0, 8)

<IPython.core.display.Javascript object>

#The relationship between vectors a, b and a - b is that a-b is the distance/displacement from the point of b to the point of a.

## 1.6 Find $c \cdot d$

\begin{align}
\vec{c} = \begin{bmatrix}7 & 22 & 4 & 16\end{bmatrix}
\qquad
\vec{d} = \begin{bmatrix}12 & 6 & 2 & 9\end{bmatrix}
\end{align}


In [201]:
c = np.array([7, 22, 4, 16])
d = np.array([12, 6, 2, 9])

np.dot(c,d)

368

##  1.7 Find $e \times f$

\begin{align}
\vec{e} = \begin{bmatrix} 5 \\ 7 \\ 2 \end{bmatrix}
\qquad
\vec{f} = \begin{bmatrix} 3 \\4 \\ 6 \end{bmatrix}
\end{align}

In [202]:
e = np.array([5, 7, 2])
f = np.array([3, 4, 6])

np.cross(e,f)

array([ 34, -24,  -1])

## 1.8 Find $||g||$ and then find $||h||$. Which is longer?

\begin{align}
\vec{g} = \begin{bmatrix} 1 \\ 1 \\ 1 \\ 8 \end{bmatrix}
\qquad
\vec{h} = \begin{bmatrix} 3 \\3 \\ 3 \\ 3 \end{bmatrix}
\end{align}

In [203]:
g = np.array([1, 1, 1, 8])
h = np.array([3, 3, 3, 3])

print('||g|| = ',np.linalg.norm(g))
print('||h|| = ',np.linalg.norm(h))
print('||h|| is longer...')

||g|| =  8.18535277187245
||h|| =  6.0
||h|| is longer...


# Part 2 - Matrices

## 2.1 What are the dimensions of the following matrices? Which of the following can be multiplied together? See if you can find all of the different legal combinations.
\begin{align}
A = \begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix}
\qquad
B = \begin{bmatrix}
2 & 4 & 6 \\
\end{bmatrix}
\qquad
C = \begin{bmatrix}
9 & 6 & 3 \\
4 & 7 & 11
\end{bmatrix}
\qquad
D = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
\qquad
E = \begin{bmatrix}
1 & 3 \\
5 & 7
\end{bmatrix}
\end{align}

In [0]:
A = np.array([[1,3,5], [2,4,6]])
B = np.array([2,4,6])
C = np.array([[9,4], [6,7], [3,11]])
D = np.array([[1,0,0], [0,1,0], [0,0,1]])
E = np.array([[1,5], [3,7]])

#The follow matrices can multiply with each other
A with C

A with E

B with D

C with D

D with D

E with C


In [205]:
print('A is 3x2')
print('B is 1x3')
print('C is 2x3')
print('D is 3x3')
print('E is 2x2')

A is 3x2
B is 1x3
C is 2x3
D is 3x3
E is 2x2


## 2.2 Find the following products: CD, AE, and BA. What are the dimensions of the resulting matrices? How does that relate to the dimensions of their factor matrices?

In [206]:
#print('CD =', np.dot(C,D))
#print('AE =', np.dot(A,E))
#print('BA =', np.dot(B,A))
print('CD =', np.cross(C,D))
print('AE =', np.cross(A,E))
print('BA =', np.cross(B,A))

CD = [[ 0  0 -4]
 [ 0  0  6]
 [11 -3  0]]
AE = [[-25   5   2]
 [-42  18   2]]
BA = [[ 2 -4  2]
 [ 0  0  0]]


## 2.3  Find $F^{T}$. How are the numbers along the main diagonal (top left to bottom right) of the original matrix and its transpose related? What are the dimensions of $F$? What are the dimensions of $F^{T}$?

\begin{align}
F = 
\begin{bmatrix}
20 & 19 & 18 & 17 \\
16 & 15 & 14 & 13 \\
12 & 11 & 10 & 9 \\
8 & 7 & 6 & 5 \\
4 & 3 & 2 & 1
\end{bmatrix}
\end{align}

In [0]:
F = [[20,16,12,8,4], [19,15,11,7,3], [18,14,10,6,2], [17,13,9,5,1]]

In [208]:
Ft = np.transpose(F)
Ft.shape

(5, 4)

In [209]:
F = np.transpose(Ft)
F.shape

(4, 5)

# Part 3 - Square Matrices

## 3.1 Find $IG$ (be sure to show your work) 😃

You don't have to do anything crazy complicated here to show your work, just create the G matrix as specified below, and a corresponding 2x2 Identity matrix and then multiply them together to show the result. You don't need to write LaTeX or anything like that (unless you want to).

\begin{align}
G= 
\begin{bmatrix}
13 & 14 \\
21 & 12 
\end{bmatrix}
\end{align}

In [0]:
G = np.array([[13,21], [14,12]])
I = np.linalg.inv(G)

In [211]:
np.dot(I,G)

array([[1.00000000e+00, 1.11022302e-16],
       [2.77555756e-17, 1.00000000e+00]])

## 3.2 Find $|H|$ and then find $|J|$.

\begin{align}
H= 
\begin{bmatrix}
12 & 11 \\
7 & 10 
\end{bmatrix}
\qquad
J= 
\begin{bmatrix}
0 & 1 & 2 \\
7 & 10 & 4 \\
3 & 2 & 0
\end{bmatrix}
\end{align}


In [0]:
H = np.array([[12,7],[11,10]])
J = np.array([[0,7,3], [1,10,2], [2,4,0]])

In [213]:
print('|H| = ', np.linalg.det(H))
print('|J| = ', np.linalg.det(J))

|H| =  43.000000000000014
|J| =  -19.999999999999996


## 3.3 Find $H^{-1}$ and then find $J^{-1}$

In [214]:
H1 = np.linalg.inv(H)
J1 = np.linalg.inv(J)
print('H^-1 = ', H1)
print('')
print('J^-1 = ', J1)

H^-1 =  [[ 0.23255814 -0.1627907 ]
 [-0.25581395  0.27906977]]

J^-1 =  [[ 0.4  -0.6   0.8 ]
 [-0.2   0.3  -0.15]
 [ 0.8  -0.7   0.35]]


## 3.4 Find $HH^{-1}$ and then find $J^{-1}J$. Is $HH^{-1} == J^{-1}J$? Why or Why not? 

Please ignore Python rounding errors. If necessary, format your output so that it rounds to 5 significant digits (the fifth decimal place).

In [215]:
np.dot(H,H1)

array([[1.00000000e+00, 1.11022302e-16],
       [1.11022302e-16, 1.00000000e+00]])

In [216]:
np.dot(J1,J)

array([[ 1.0000000e+00, -4.4408921e-16,  0.0000000e+00],
       [ 0.0000000e+00,  1.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  1.0000000e+00]])

# Stretch Goals: 

A reminder that these challenges are optional. If you finish your work quickly we welcome you to work on them. If there are other activities that you feel like will help your understanding of the above topics more, feel free to work on that. Topics from the Stretch Goals sections will never end up on Sprint Challenges. You don't have to do these in order, you don't have to do all of them. 

- Write a function that can calculate the dot product of any two vectors of equal length that are passed to it.
- Write a function that can calculate the norm of any vector
- Prove to yourself again that the vectors in 1.9 are orthogonal by graphing them. 
- Research how to plot a 3d graph with animations so that you can make the graph rotate (this will be easier in a local notebook than in google colab)
- Create and plot a matrix on a 2d graph.
- Create and plot a matrix on a 3d graph.
- Plot two vectors that are not collinear on a 2d graph. Calculate the determinant of the 2x2 matrix that these vectors form. How does this determinant relate to the graphical interpretation of the vectors?

